### PR TITLE
DM-30155: Add deprecation to the get_catalog function

### PR DESCRIPTION
**Pull request by SimonKrughoff**
This also exposes the renamed get_TAPService function

### CODE REVIEW

**Review by athornton — COMMENTED** [review]
Why not use Deprecated?  https://pypi.org/project/Deprecated/

**Comment by SimonKrughoff** [comment]
I didn't want to add another dependency.

**Review by athornton — APPROVED** [review]

**Review by athornton — APPROVED** [review]
LGTM

**Review by athornton — COMMENTED** [review]
Actually hang on lemme bump the version

**Pull request merged**
